{% set name = "pip-tools" %}
{% set version = "6.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b4762359978fd81a2b4b666e6dca15266bdc65680d06900c4da34243f35e4b5d

build:
  number: 0
  noarch: python
  entry_points:
    - pip-compile = piptools.scripts.compile:cli
    - pip-sync = piptools.scripts.sync:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - click >=7
    - python-build
    - pip >=20.3
    - python >=3.6

test:
  imports:
    - piptools
  commands:
    - pip check
    - pip-compile --help
    - pip-sync --help
  requires:
    - pip

about:
  home: https://pypi.org/project/pip-tools/
  summary: pip-tools keeps your pinned dependencies fresh.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
